
sudo: required
dist: xenial

language: cpp
compiler: gcc
os:
- linux

env:
  - OMP_NUM_THREADS=4

before_install:
  - sudo apt-get -qq update
# end

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcfitsio3-dev
    - libgsl-dev
    - libnlopt-dev
    - cxxtest
    - scons

# Python stuff so we can run python-using scripts in regression tests.
# This needs to go *after* the C++ setup, otherwise the numpy install doesn't work...
language: python
python:
  # Travis CI xenial (Ubuntu 16.04) has Python 3.6 and 3.7 pre-installed
  - 3.6
cache: pip

install:
  - pip install numpy
  - pip install astropy

script: 
  - ./run_unit_tests.sh
  - scons makeimage
  - scons imfit
  - scons imfit-mcmc
  - ./do_makeimage_tests

# Note that running do_imfit_tests tends to produce the usual Linux-vs-OSX output mismatches
# in the final decimal places for some of the outputs (probably due to subtle
# floating-point issues), and sometimes mysterious segfaults.
after_success:
  - ./do_imfit_tests
  - ./do_mcmc_tests

